all: ex1.exe ex2.exe ex3.exe ex4.exe #ex5.exe ex6.exe ex7.exe ex8.exe ex9.exe ex10.exe ex11.exe ex12.exe ex13.exe ex14.exe ex15.exe ex16.exe ex17.exe ex18.exe ex19.exe ex20.exe ex21.exe ex22.exe ex23.exe ex24.exe ex25.exe ex26.exe

%.exe: %.c
	gcc -o $@ $^
